---
- hosts: all
sudo: yes
gather_facts: yes
pre_tasks:
- name: Ensure Ansible dependencies are installed.
yum: pkg=libselinux-python state=installed
roles:
- geerlingguy.nfs
- geerlingguy.packer-rhel